### PR TITLE
Add a context manager for zipping FASTX files

### PR DESCRIPTION
**Pull request by clintval**
Helpful addition? Docs appear to render correctly on my local machine:

Screenshot 2023-11-24 at 1 04 03 PM

### CODE REVIEW

**Review by nh13 — COMMENTED** [review]
Shall we suggest adding this to pysam to the pysam developers?

**Comment by clintval** [comment]
> Shall we suggest adding this to pysam to the pysam developers?

What's been your approach on this for pysam vs fgpyo? I'm up for it!

I have a few more PRs to make in pysam for all matter of wrong docs, bugs, and features I recently found.

**Comment by nh13** [comment]
> What's been your approach on this for pysam vs fgpyo? I'm up for it!

I ask first, and it's nice that you can point it to here (and we can even merge it!)

**Review by nh13 — APPROVED** [review]

**Comment by clintval** [comment]
I want to add one more defensive check to make sure the class isn't used as an Iterator outside of the context manager context (which would result in a bug). Just thought of that edge case prior to merge!

**Comment by clintval** [comment]
@nh13 I added one more commit and feel good with the functionality.

Let me know if you'd like to re-review!

**Comment by nh13** [comment]
No need for me to re review. Ship it!

**Pull request merged**
